SET PATH=D:\Maker\keil5\ARM\ARMCC\Bin;C:\Windows;C:\Windows\system32;C:\Windows\System32\Wbem;C:\Windows\System32\OpenSSH\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\exe\cmder;D:\exe\Notepad3;C:\Program Files\dotnet\;D:\Program Files\Git\cmd;D:\Program Files\mingw64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\ProgramTools\HelpTools\Network\Xshell_7.0\;D:\ProgramTools\;D:\Maker\Anaconda;D:\Maker\Anaconda\Library\mingw-w64\bin;D:\Maker\Anaconda\Library\usr\bin;D:\Maker\Anaconda\Library\bin;D:\Maker\Anaconda\Scripts;D:\exe\Fiddler;C:\Users\16377\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;D:\Program Files\VSCode\Microsoft VS Code\bin;C:\Users\16377\AppData\Local\Microsoft\WindowsApps;D:\Maker\PyCharm\PyCharm 2020.2.2\bin;C:\Users\16377\.dotnet\tools
SET CPU_TYPE=STM32F407ZG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Proj
SET CPU_CLOCK=0x00B71B00
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\misc.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_adc.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_can.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_dac.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_dma.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_flash.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_exti.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_gpio.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_fsmc.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_iwdg.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_i2c.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmCC" --Via ".\obj\stm32f4xx_rcc.__i"
"D:\Maker\keil5\ARM\ARMCC\Bin\ArmLink" --Via ".\Obj\Proj.lnp"
